### ISSUE TITLE
how do I add more then one switch?

### ISSUE THREAD

**Issue by luckyzor** [aschor/HASS_template_REST_switch#1]
I have 2 switch on my moonracker config, the printer and the LEDS.

How I can do to add 2 switchs?

thanks

**Comment by aschor** [comment]
hi,

like this :

```
switch:
  - platform: template_rest_switch
    name: "moonraker Leds printer 1"
    ...etc
  - platform: template_rest_switch
    name: "moonraker Leds printer 2"
    ...etc
```
